### PR TITLE
icecat: Add params, prevent reboot

### PR DESCRIPTION
**Pull request by brian6932**

### CODE REVIEW

**Review by TheCakeIsNaOH — CHANGES_REQUESTED** [review]
These should not be added directly to the silent args, instead, they should be available through package parameters. 
https://docs.chocolatey.org/en-us/guides/create/parse-packageparameters-argument/

**Comment by brian6932** [comment]
@TheCakeIsNaOH For some reason whenever I try to install nupkgs locally with choco now, I get the error below, I didn't used to have these issues with the old `choco install <package>.nupkg` syntax. Idk what could be causing this problem, makes testing here a bit more annoying than it should be, Any ideas?
```
❯ choco pack; choco install <package> --source=$pwd -f
Chocolatey v2.3.0
Attempting to build package from '<package>.nuspec'.
Successfully created package "$pwd\<package>.<version>.nupkg"

WARNING: May not be able to find 'C:\ProgramData\chocolatey\lib\<package>\tools\<exe>'. Please use full path for executables.
ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
The install of <package> was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\<package>\tools\chocolateyinstall.ps1'.
```

**Comment by TheCakeIsNaOH** [comment]
> Idk what could be causing this problem, makes testing here a bit more annoying than it should be. Any ideas?

That functionality was removed, instead use a source of the directory that the nupkg is in.
https://github.com/chocolatey/choco/issues/3008

**Comment by brian6932** [comment]
I know that it's removed, I'm  trying to say the new method's not working for me, and the previous one did, that's what the logs were for.

**Comment by TheCakeIsNaOH** [comment]
So you have to first run `choco pack` to pack up the nuspec into a nupkg, then you have to run `choco install <package> --source=path` to install the nupkg. The log provided looks like you were trying to install the nuspec directly.

As for the `.exe` missing, the binaries don't get committed to this repository. So you have to either force run the `update.ps1` script which will download the `.exe`, or you have to manually download the `.exe` into the tools folder and then pack the package.

**Comment by brian6932** [comment]
> manually download the `.exe` into the tools folder and then pack the package.

I believe I tried to do this, and still had the same error. It very well could've been some user error, or me not packing specifically after, but just running the already packed nupkg. It seemed to fail and delete the executable.

> So you have to first run `choco pack` to pack up the nuspec into a nupkg, then you have to run `choco install <package> --source=path` to install the nupkg. The log provided looks like you were trying to install the nuspec directly.

My working dir's the package dir, and I just set source to `$pwd`, which's the working dir.

**Comment by TheCakeIsNaOH** [comment]
> I put it in the ProgramData dir, was I supposed to put it in the working dir? 

Put in the `tools` directory under the package source, so inside this cloned git repository. Then when `choco pack` is run, the `.exe` is put inside the `.nupkg`, and then extracted again during installation into that directory under programdata.

**Comment by brian6932** [comment]
```pwsh
❯ ls tools

        Directory: ...\icecat\tools


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---        2024-10-14  11:52 PM            851 󰞷  chocolateyinstall.ps1
-a---        2024-10-13   1:43 PM            797 󰞷  chocolateyuninstall.ps1
-a---        2024-10-15   1:15 AM       69489576 󰣆  icecat-115.16.1.en-US.win64.installer.exe

❯ choco pack; choco install icecat --source=$pwd -f
Chocolatey v2.3.0
Attempting to build package from 'icecat.nuspec'.
Successfully created package '...\icecat\icecat.115.16.1.nupkg'
Chocolatey v2.3.0
Installing the following packages:
icecat
By installing, you accept licenses for the packages.
Downloading package from source '...\icecat'

icecat v115.16.1 (forced)
icecat package files install completed. Performing other installation steps.
PRE-INSTALLATION CHECKS:
  * WARNING: Pending reboot found.
  * Windows Installer IS NOT currently running
  * choco.exe IS NOT running multiple instances.
Installing 64-bit icecat...
WARNING: May not be able to find 'C:\ProgramData\chocolatey\lib\icecat\tools\icecat-115.16.1.en-US.win64.installer_x64.exe'. Please use full path for executables.
ERROR: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
The install of icecat was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\icecat\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - icecat (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\icecat\tools\chocolateyinstall.ps1'.
 See log for details.

Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip-top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare
```

**Comment by TheCakeIsNaOH** [comment]
The in your tools directory is named 
`icecat-115.16.1.en-US.win64.installer.exe` 
The install script is looking for                                 
`icecat-115.16.1.en-US.win64.installer_x64.exe`

**Comment by brian6932** [comment]
Thank you, that works, I just downloaded the file from https://icecatbrowser.org/assets/icecat/115.16.1/icecat-115.16.1.en-US.win64.installer.exe 🤦‍♂️ seems like my changes aren't working though, I can go in not blind now.

**Comment by TheCakeIsNaOH** [comment]
Yup, the `chocolatey-au` module by adds the arch to the filename, and I must have not disabled it for this package.

**Review by TheCakeIsNaOH — CHANGES_REQUESTED** [review]
The package parameters should also be documented in the package description.
Example: https://github.com/TheCakeIsNaOH/chocolatey-packages/blob/6731c675dfff9657cd0904c9eb0e084912c663e8/4k-slideshow-maker/4k-slideshow-maker.nuspec#L21-L27

**Comment by brian6932** [comment]
Is there a way to see what the output of `Get-PackageParameters` parses commands into?

**Comment by TheCakeIsNaOH** [comment]
It should show up if you use `--debug` with the choco install command. I'm not sure if that is what you are wanting?

**Comment by brian6932** [comment]
> The package parameters should also be documented in the package description.

Is it ok to link to the official installer documentation here, and mention the default changes? The formatting's the same, and I think it'd reduce the maintenance burden for this package.

**Comment by TheCakeIsNaOH** [comment]
Apologies for the late reply, I've been busy with other things. 

When I mentioned that the items should be available through package parameters, I had intended to mention that the defaults should not be changed, so by default the package should still have the default installer behavior. Then if people want to select other options, they can do so through package parameters.

Each package parameter should have explicit documentation in the description, and explicit handling in the install script. 

If you just want to pass installer arguments, that can be done directly with the `--install-arguments=VALUE` argument to the `choco install`/`upgrade` commands

Hopefully that makes sense, let me know if I can clarify further.

**Comment by brian6932** [comment]
> I had intended to mention that the defaults should not be changed, so by default the package should still have the default installer behavior. Then if people want to select other options, they can do so through package parameters.

Ok, but do these get persisted? I don't think the defaults are very sane, if not.

**Comment by TheCakeIsNaOH** [comment]
> Ok, but do these get persisted? I don't think the defaults are very sane, if not.

If you turn on the `useRememberedArgumentsForUpgrades ` feature. It is currently not on by default, but hopefully will be in the next few Chocolatey CLI releases.

**Review by TheCakeIsNaOH — APPROVED** [review]
LGTM

**Pull request merged**
